## ECG Data Compression Wavelet Transform Method
Based on "Effective high compression of ECG signals at low level distortion" by Laura Rebollo-Neira

### Step 0: Import Libraries

In [4]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import iqr
import sys
import copy
from scipy.signal import detrend
import copy 

### Load Data

In [5]:
import mne
file = "/Users/juseo\Documents\dyuku\summer 20\dbdp\code\DBDP_Compression_Toolbox/Joe/ECG.EDF"
data = mne.io.read_raw_edf(file)
raw_data = data.get_data()

import numpy as np
header = ','.join(data.ch_names)
np.savetxt('ECG.csv', data.get_data().T, delimiter=',', header=header)

import pandas as pd
df0 = pd.read_csv('ECG.csv')
df = df0.iloc[:,0:1]

Extracting EDF parameters from C:\Users\juseo\Documents\dyuku\summer 20\dbdp\code\DBDP_Compression_Toolbox\Joe\ECG.EDF...
EDF file detected
Setting channel info structure...
Creating raw.info structure...


In [6]:
df

# ECG
0        0.032767
1        0.032767
2        0.032767
3        0.032767
4        0.032767
5        0.032767
6        0.032767
7        0.032767
8        0.032767
9        0.032767
10       0.032767
11       0.032767
12       0.032767
13       0.032767
14       0.032767
15       0.032767
16       0.032767
17       0.032767
18       0.032767
19       0.032767
20       0.032767
21       0.032767
22       0.032767
23       0.032767
24       0.032767
25       0.032767
26       0.032767
27       0.032767
28       0.032767
29       0.032767
...           ...
3269970  0.001328
3269971  0.001635
3269972  0.001904
3269973  0.002159
3269974  0.002415
3269975  0.002565
3269976  0.002626
3269977  0.002605
3269978  0.002454
3269979  0.002157
3269980  0.001857
3269981  0.001574
3269982  0.001299
3269983  0.001146
3269984  0.001077
3269985  0.001091
3269986  0.001212
3269987  0.001434
3269988  0.001726
3269989  0.002014
3269990  0.002283
3269991  0.002487
3269992  0.002576
3269993  0.002598
3269994  0.002521
3269995  0.002334
3269996  0.002037
3269997  0.001726
3269998  0.001404
3269999  0.001145

[3270000 rows x 1 columns]

### Step 1: Approximation
**Input:** Array **w** of wavelets coefficients & parameter *tol* for the approximation error  
**Output:** Indices *l*<sub>i</sub>, i=1,...,*K* of the selected wavelet coefficients. Array **c** with the selected wavelet coefficients.

#### Part A: DWT transform
Array *data* with the N-dimensional signal. Decomposition level *lv*.  
Wavelet used: bior4.4.

In [7]:
import pywt
from pywt import wavedec
def dwt(data, lv):
    cA5, cD5, cD4, cD3, cD2, cD1 = wavedec(data, 'bior4.4', level=lv)
    coeffs = {'cA5': cA5, 'cD5': cD5, 'cD4': cD4, 'cD3': cD3, 'cD2': cD2, 'cD1': cD1}
    return coeffs

In [9]:
coeffs = dwt(df,5)

In [13]:
coeffs

{'cA5': array([[0.18535814, 0.18535814, 0.18535814, ..., 0.18535814, 0.18535814,
         0.18535814],
        [0.18535814, 0.18535814, 0.18535814, ..., 0.18535814, 0.18535814,
         0.18535814],
        [0.18535814, 0.18535814, 0.18535814, ..., 0.18535814, 0.18535814,
         0.18535814],
        ...,
        [0.00976373, 0.00976373, 0.00976373, ..., 0.00976373, 0.00976373,
         0.00976373],
        [0.00794222, 0.00794222, 0.00794222, ..., 0.00794222, 0.00794222,
         0.00794222],
        [0.0064771 , 0.0064771 , 0.0064771 , ..., 0.0064771 , 0.0064771 ,
         0.0064771 ]]),
 'cD5': array([[-1.85382959e-13, -1.85382959e-13, -1.85382959e-13, ...,
         -1.85382959e-13, -1.85395102e-13, -1.85382959e-13],
        [-1.85382959e-13, -1.85382959e-13, -1.85382959e-13, ...,
         -1.85382959e-13, -1.85395102e-13, -1.85382959e-13],
        [-1.85382959e-13, -1.85382959e-13, -1.85382959e-13, ...,
         -1.85382959e-13, -1.85395102e-13, -1.85382959e-13],
        ...,
    

In [12]:
recon = pywt.waverec([coeffs['cA5'], coeffs['cD5'], coeffs['cD4'], coeffs['cD3'], 
                                    coeffs['cD2'], coeffs['cD1']], 'bior4.4')

In [14]:
recon

array([[0.032767, 0.032767],
       [0.032767, 0.032767],
       [0.032767, 0.032767],
       ...,
       [0.001726, 0.001726],
       [0.001404, 0.001404],
       [0.001145, 0.001145]])

Wavelet Object: https://pywavelets.readthedocs.io/en/latest/regression/wavelet.html  
DWT API: https://pywavelets.readthedocs.io/en/latest/ref/dwt-discrete-wavelet-transform.html#ref-dwt   
Handling DWT Coeffs: https://pywavelets.readthedocs.io/en/latest/ref/dwt-coefficient-handling.html

#### Part B: Selection of the largest wavelet coefficients

Thresholds the wavelet coefficients to a specified energy.  
Different levels of decomposition are thresholded at different energy percentages.
1. Calculate the energy of all the coefficients.
1. Sort the coefficients from highest to lowest.
1. Calculate the energy as each new coefficient is added.
1. Repeat until the percentage is above the threshold.

In [15]:
#sort the absolute value of the coefficients in descending order
tmp_coeffs = np.sort(np.abs(coeffs['cA5']))

In [16]:
tmp_coeffs

array([[0.18535814, 0.18535814, 0.18535814, ..., 0.18535814, 0.18535814,
        0.18535814],
       [0.18535814, 0.18535814, 0.18535814, ..., 0.18535814, 0.18535814,
        0.18535814],
       [0.18535814, 0.18535814, 0.18535814, ..., 0.18535814, 0.18535814,
        0.18535814],
       ...,
       [0.00976373, 0.00976373, 0.00976373, ..., 0.00976373, 0.00976373,
        0.00976373],
       [0.00794222, 0.00794222, 0.00794222, ..., 0.00794222, 0.00794222,
        0.00794222],
       [0.0064771 , 0.0064771 , 0.0064771 , ..., 0.0064771 , 0.0064771 ,
        0.0064771 ]])

In [49]:
print(len(tmp_coeffs))
print(len(coeffs['cA5']))
print(coeffs['cA5'][3269999])

3270000
3270000
[0.0064771 0.0064771 0.0064771 0.0064771 0.0064771 0.0064771 0.0064771
 0.0064771]


In [36]:
#find cumulative sum of square of each value
csums = np.cumsum(np.square(tmp_coeffs),axis=0)

In [37]:
csums

array([[3.43576412e-02, 3.43576412e-02, 3.43576412e-02, ...,
        3.43576412e-02, 3.43576412e-02, 3.43576412e-02],
       [6.87152825e-02, 6.87152825e-02, 6.87152825e-02, ...,
        6.87152825e-02, 6.87152825e-02, 6.87152825e-02],
       [1.03072924e-01, 1.03072924e-01, 1.03072924e-01, ...,
        1.03072924e-01, 1.03072924e-01, 1.03072924e-01],
       ...,
       [1.34987590e+03, 1.34987590e+03, 1.34987590e+03, ...,
        1.34987590e+03, 1.34987590e+03, 1.34987590e+03],
       [1.34987597e+03, 1.34987597e+03, 1.34987597e+03, ...,
        1.34987597e+03, 1.34987597e+03, 1.34987597e+03],
       [1.34987601e+03, 1.34987601e+03, 1.34987601e+03, ...,
        1.34987601e+03, 1.34987601e+03, 1.34987601e+03]])

In [19]:
#approximation error parameter
tol = 1

In [38]:
#set any coefficients below the threshold to zero
inds_to_zero = np.where((csums < tol))[0]
csums[inds_to_zero] = 0

In [39]:
inds_to_zero

array([ 0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  2,
        2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,
        4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,
        6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,
        8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10,
       10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12,
       12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14,
       14, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16,
       17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 19,
       19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21,
       21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 23, 23, 23,
       23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25,
       25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27,
       27, 27, 27, 28, 28

In [40]:
csums

array([[   0.        ,    0.        ,    0.        , ...,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        , ...,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        , ...,    0.        ,
           0.        ,    0.        ],
       ...,
       [1349.87590287, 1349.87590287, 1349.87590287, ..., 1349.87590287,
        1349.87590287, 1349.87590287],
       [1349.87596595, 1349.87596595, 1349.87596595, ..., 1349.87596595,
        1349.87596595, 1349.87596595],
       [1349.8760079 , 1349.8760079 , 1349.8760079 , ..., 1349.8760079 ,
        1349.8760079 , 1349.8760079 ]])

In [41]:
nonzero_coeff_count = len(csums)

In [42]:
nonzero_coeff_count

3270000

In [43]:
np.nonzero(csums)

(array([     29,      29,      29, ..., 3269999, 3269999, 3269999],
       dtype=int64), array([0, 1, 2, ..., 5, 6, 7], dtype=int64))

In [30]:
#indices of absolute value of coefficients that would sort in ascending order
indices = np.argsort(np.abs(coeffs['cA5']),axis=0)
indices

array([[2718562, 2718562, 2718562, ..., 2718562, 2718562, 2718562],
       [2227161, 2227161, 2227161, ..., 2227161, 2227161, 2227161],
       [2713764, 2713764, 2713764, ..., 2713764, 2713764, 2713764],
       ...,
       [ 110410,  110410,  110410, ...,  110410,  110410,  110410],
       [ 122845,  122845,  122845, ...,  122845,  122845,  122845],
       [ 110612,  110612,  110612, ...,  110612,  110612,  110612]],
      dtype=int64)

In [35]:
len(indices)

3270000

In [48]:
inds_to_keep = np.where((indices > 29))[0]
inds_to_keep

array([      0,       0,       0, ..., 3269999, 3269999, 3269999],
      dtype=int64)

In [55]:
np.swapaxes(coeffs['cA5'],0,1)

array([[0.18535814, 0.18535814, 0.18535814, ..., 0.00976373, 0.00794222,
        0.0064771 ],
       [0.18535814, 0.18535814, 0.18535814, ..., 0.00976373, 0.00794222,
        0.0064771 ],
       [0.18535814, 0.18535814, 0.18535814, ..., 0.00976373, 0.00794222,
        0.0064771 ],
       ...,
       [0.18535814, 0.18535814, 0.18535814, ..., 0.00976373, 0.00794222,
        0.0064771 ],
       [0.18535814, 0.18535814, 0.18535814, ..., 0.00976373, 0.00794222,
        0.0064771 ],
       [0.18535814, 0.18535814, 0.18535814, ..., 0.00976373, 0.00794222,
        0.0064771 ]])

In [56]:
selected = coeffs['cA5'][inds_to_keep]

In [65]:
np.swapaxes(selected,0,1)

array([[0.18535814, 0.18535814, 0.18535814, ..., 0.0064771 , 0.0064771 ,
        0.0064771 ],
       [0.18535814, 0.18535814, 0.18535814, ..., 0.0064771 , 0.0064771 ,
        0.0064771 ],
       [0.18535814, 0.18535814, 0.18535814, ..., 0.0064771 , 0.0064771 ,
        0.0064771 ],
       ...,
       [0.18535814, 0.18535814, 0.18535814, ..., 0.0064771 , 0.0064771 ,
        0.0064771 ],
       [0.18535814, 0.18535814, 0.18535814, ..., 0.0064771 , 0.0064771 ,
        0.0064771 ],
       [0.18535814, 0.18535814, 0.18535814, ..., 0.0064771 , 0.0064771 ,
        0.0064771 ]])

In [66]:
len(np.swapaxes(selected,0,1)[0])

26159760

In [64]:
len(selected)

26159760

In [50]:
select = coeffs['cA5'][np.argwhere(csums > tol)]

IndexError: index 3270000 is out of bounds for axis 0 with size 3270000

In [ ]:
def threshold_energy(coeffs):
    #make a deep copy of coeffs to retain the original version
    coeffs_orig = copy.deepcopy(coeffs)

    binary_map = {}
    nonzero_coeff_count = {}

    for key in coeffs.keys():
        #sort the absolute value of the coefficients in ascending order
        tmp_coeffs = np.sort(np.abs(coeffs[key]))

        #calculate the threshold for retaining some percentage of the energy
        if key == 'cA5':
            thresh_perc = THRESH_PERC_APPROX
        elif key == 'cD5':
            thresh_perc = THRESH_PERC_D5
        else:
            thresh_perc = THRESH_PERC_D4_D1

        energy_thresholded = thresh_perc*energy(tmp_coeffs)
        energy_tmp = 0
        for coeff in tmp_coeffs:
            energy_tmp = energy_tmp + coeff**2

            if energy_tmp >= energy_thresholded:
                threshold = coeff
                break

        #set any coefficients below the threshold to zero
        tmp_coeffs = coeffs[key]
        inds_to_zero = np.where((tmp_coeffs < threshold) & (tmp_coeffs > -threshold))[0]
        tmp_coeffs[inds_to_zero] = 0
        
        #create array of selected wavelet coefficients
        coeffs[key] = tmp_coeffs
        nonzero_coeff_count[key] = len(tmp_coeffs)
        
    return nonzero_coeff_count   

### Step 2: Quantization
A mid-tread uniform quantizer transforms the selected wavelet coefficients into integers.

Scale the wavelet coefficients to the [0,1] range.

In [ ]:
def scale_coeffs(coeffs, do_plot=False):
    coeffs_scaled = {}
    scaling_factors = {}

    for key in coeffs.keys():
        shift_factor = np.min(coeffs[key])
        coeffs_tmp = coeffs[key]-shift_factor

        scale_factor = np.max(coeffs_tmp)
        coeffs_tmp = coeffs_tmp/scale_factor

        scaling_factors[key] = {'shift_factor': shift_factor, 'scale_factor': scale_factor}
        coeffs_scaled[key] = coeffs_tmp
    return coeffs_scaled, scaling_factors

Calculate the lowest possible number of bits to quantize the wavelet coefficients such that the PRD is above the threshold.
1. Quantize the signal starting at 8 bits
1. Unquantize and reconstruct the signal
1. Calculate the PRD.
1. Repeat with 1 fewer bit (ie, 7 bits), ...

In [ ]:
def calculate_num_bits(orig_sig, coeffs_scaled, binary_map, scaling_factors, do_plot=False):
    #starting at 8 bits, keep decreasing the number of bits in the quantization
    #until the PRD is above some threshold
    num_bits = 9

    #initialize PRD to 0 so the while loop can run
    PRD = 0

    #keep track of PRD per number of bits
    PRD_dict = {}
    
    while (num_bits >= 5) and (PRD <= MAX_PRD):
        #decrement the number of bits
        num_bits = num_bits-1

        coeffs_quantized = do_quantization(coeffs_scaled, num_bits)

        #rescale the coefficients
        coeffs_unscaled = unscale_coeffs(None, coeffs_quantized, scaling_factors, num_bits)

        #do the inverse dwt
        data_reconstructed = wavelet_reconstruction(coeffs_unscaled, None, None)

        #calculate PRD
        PRD = calculate_PRD(orig_sig, data_reconstructed)
        PRD_dict[num_bits] = PRD

        #plot the reconstructed signals 
        if do_plot:
            if PRD <= MAX_PRD:
                plt.plot(t, data_reconstructed, label='Reconstructed @ %i Bits, PRD = %.2f' % (num_bits, PRD))

    #if we went over the PRD, go back up by one bit
    if PRD > MAX_PRD:
        num_bits = num_bits+1
        PRD = PRD_dict[num_bits]
    
    return num_bits, PRD

Quantization:
1. Take in the scaled wavelet coefficients
1. Multiply by 2^(num bits)
1. Round to the nearest integer.

In [ ]:
def do_quantization(coeffs, bits, do_plot=False):
    quantized_coeffs = {}

    for key in coeffs.keys():
        sig = coeffs[key]
        sig = sig*(2**bits-1)
        sig = np.round(sig)
        sig = np.array(sig).astype(int)

        quantized_coeffs[key] = sig
        
    return quantized_coeffs

### Step 3: Organization and Storage Step
1. Re-order indices in ascending order. This re-orders coefficients and corresponding signs.
1. Store re-ordered indices as smaller positive numbers by taking differences between two consecutive values. 
1. Save the size of the singal, the quantization parameter, and the arrays (reordered coefficients, signs, and indices) in HDF5 format.

#### Reference MATLAB Code

In [ ]:
#
clear 
# Options
baseline=0 # does not modify raw data
mywname='cdf97' # wavelet family
wlevel=4 # decomposition level
store=0 # Change to 1 to add Huffman entropy coding

dat=input('Please enter record number (from the MIT_BIHA_database) \n ','s');
icase=input('Please enter approximation method (a or b) \n','s');
if icase=='a'
PRD0=input('Please enter PRD0 (e.g. 0.4217)  \n');
end

del=input('Please enter quantization parameter (e.g. 32 for a) and 39 for b) \n');
%

filenamer=['ECG_Compression/MIT_BIHA_DATA/Record_' char(strcat(dat, '_11bits.dat'))];
filenamew_tmp='ECG_Compression/Comp_Record.mat'
fid=fopen(filenamer,'r');
f=fread(fid,'ubit11');
fclose(fid);

f=f-baseline;
tic
base=0;
[fw,wl]=mydwt(f,wlevel,mywname);
L=numel(fw);
if icase=='a'
tol=PRD0*norm(f)/100;
[cs,wind]=SLWC(fw,tol);
end
if icase=='b'
cs=fw;
wind=1:numel(fw);
wind=wind';
end

# quantization of wavelet coefficients
csq=sign(cs).*floor(abs(cs)/del+0.5);
I0=find(csq==0);
if isempty(I0)==0 # remove the zeros
csq(I0)=[];
wind(I0)=[];
end

# Organization and Storage
clear vc vi vs
[or,ior]=sort(wind); # sort the indices
vc=abs(csq(ior)); 

# take differences
vi=[or(1) diff(or)'];
# invert with cumsum([vi]);
# vi=vdif(or); # take differences
vs=(sign(csq(ior))+ 1)./2; # encode the signs as zeros and ones

if store==0;
save (filenamew_tmp, 'del','L', 'vi', 'vc', 'vs'); # save in HDF5 format
else
xS{1}=vs;
xC{1}=vi;
xCC{1}=vc;
ys=Huff06(xS);
yc=Huff06(xCC);
yi=Huff06(xC);
save (filenamew_tmp, 'del','L','yi','yc','ys'); # save in HDF5 format
end
hf11=dir(filenamer);
hfH=dir(filenamew_tmp);
CR=hf11.bytes/hfH.bytes #calculate CR
toc

## Data Reconstruction

### Wavelet Reconstruction

In [ ]:
def dwt_reconstruct(coeffs):
    reconstructed = pywt.waverec([coeffs['cA5'], coeffs['cD5'], coeffs['cD4'], coeffs['cD3'], 
                                    coeffs['cD2'], coeffs['cD1']], 'bior4.4')
    return reconstructed